Performance without filter builder
GGM-Gastro/ListSuspectProducts pull request #1
Opened 2021-12-13 09:44 UTC by ggmsm

2021-12-13 10:11 UTC, DanielRichters requested changes

2021-12-13 10:11 UTC, DanielRichters commented on src/Controller/DefaultController.php
> +                $f=[];
Das erscheint mir unnötig.

2021-12-13 10:11 UTC, DanielRichters commented on src/Controller/DefaultController.php
> +                $f=[];
Das erscheint mir unnötig.

2021-12-13 10:11 UTC, DanielRichters commented on src/Repository/AkeneoProductRepository.php
> +    public function findAllProducts($fields = [])
$fields wird nicht genutzt

2021-12-13 10:11 UTC, DanielRichters commented on templates/default/index.html.twig
> +        let f = {{ fields|json_encode|raw }};
Das Naming ist fragwürdig.

2021-12-13 10:11 UTC, DanielRichters commented on src/Controller/DefaultController.php
> +        $f = [];
Das Naming ist fragwürdig.

2021-12-14 06:42 UTC, ggmsm commented on src/Controller/DefaultController.php
> +            ['code' => 'name2_de', 'type'=>'string']
habe mich hierfür entschieden:
`private function includeStandardFields(array $fields = []): array`

2021-12-14 08:19 UTC, DanielRichters approved these changes

2021-12-14 08:31 UTC, merged